# Twitter OAuth Local Setting
twitter_key:    "fMTD5gs4Kr3l95WZtyZmaGkHo"
twitter_secret: "eXSnPp6rTKzVdVP57lOdP4vnrwOjTFRZq4xq3AtHfG6OY9JbQU"

# Facebook OAuth Setting
facebook_app_id:     "FACEBOOK_APP_ID"
facebook_app_secret: "FACEBOOK_APP_SECRET"

# GitHub OAuth Setting
github_client_id: "GITHUB_CLIENT_ID"
github_secret:    "GITHUB_SECRET"
